// TODO: Do not generate.
//
// Generated by CoffeeScript 1.6.3
'use strict';

var env, settings, yaml, _;

_ = require('underscore');

yaml = require('js-yaml');

env = require('./env');

settings = require('../config/default');

settings.env = env;

settings = _.extend(settings, require("../config/environments/" + env + ".yml"));

if (process.env.SETTINGS) {
  settings = _.extend(settings, require(process.env.SETTINGS));
} else {
  try {
    settings = _.extend(settings, require('../config/settings'));
  } catch (_error) {}
}

if (process.env.PORT) {
  settings.port = process.env.PORT;
}

module.exports = settings;
