// Generated by CoffeeScript 1.7.1
'use strict';
var configDir, env, exists, extend, file, files, fs, load, options, read, settings, _i, _len;

fs = require('fs');

read = fs.readFileSync;

exists = fs.existsSync;

load = require('js-yaml').safeLoad;

env = require('./env');

configDir = "" + (process.cwd()) + "/config";

options = {
  encoding: 'utf8'
};

settings = {};

extend = function(file) {
  var obj, prop, _results;
  obj = load(read(file, options));
  if (obj) {
    _results = [];
    for (prop in obj) {
      _results.push(settings[prop] = obj[prop]);
    }
    return _results;
  }
};

files = ["" + configDir + "/default.yml", "" + configDir + "/environments/" + env + ".yml"];

for (_i = 0, _len = files.length; _i < _len; _i++) {
  file = files[_i];
  extend(file);
}

if (process.env.SETTINGS) {
  extend(process.env.SETTINGS);
} else {
  file = "" + configDir + "/settings.yml";
  if (exists(file)) {
    extend(file);
  }
}

settings.env = env;

if (process.env.PORT) {
  settings.port = process.env.PORT;
}

module.exports = settings;
